dist: bionic
language: python
python: 3.7.2

cache:
  - pip

if: commit_message =~ /(\[BUILD\]|\[TEST\])/

install: 
  - pip install pipenv
  - pipenv sync

script: 
  - pipenv run python manage.py test

